name: CI
on:
  push:
    branches: [ "main", "add-github-actions" ]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"
