name: CI
on:
  push:
    branches: [ "main", "add-github-actions" ]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"

      - name: Install OS dependencies
        run: |
          sudo apt install -y make curl

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.18.1' # the full version of `docker-compose` command

      - name: Check docker-composer
        run: |
          docker-compose --version

      - name: Follow instruction - prepare .env file
        run: |
          cp .env.dist .env

      - name: Follow instruction Docker compose up
        run: |
          make d.up

      - name: Show docker containers
        run: |
          docker ps

      - name: Check site
        run: |
          curl 127.0.0.1

      - name: Check site
        run: |
          curl http://127.0.0.1/?status=404      

      #      - name: Follow instruction - Composer install
#        run: |
#          make composer.install

#      - uses: isbang/compose-action@v1.4.1
#        with:
#          compose-file: "./docker-compose.yaml"

      - name: Check http statuses of site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://127.0.0.1"]'
          expected: '[200]'

      - name: Check http statuses of site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://127.0.0.1", "http://127.0.0.1/?status=404"]'
          expected: '[200, 404]'



#TODO:: need to fix the issue:
#(Failed)  HTTP Status for http://localhost is 000, expected 200
#(Failed)  HTTP Status for http://localhost?status=404 is 000, expected 404