name: CI
on:
  push:
    branches: [ "main", "add-github-actions" ]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"

      - name: Install OS dependencies
        run: |
          sudo apt install -y make

      - name: Follow instruction
        run: |
          cp .env.dist .env

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"

      - name: Check http statuses of site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://localhost", "http://localhost?status=404"]'
          expected: '[200, 404]'